### ISSUE TITLE
Can't find markdown file with the id: accessing_accounts under conflux-portal

### ISSUE THREAD

**Issue by chinajinwanjun** [Conflux-Chain/conflux-developer-site#16]
```
Cannot execute yarn start caused by following error.
> Error: Can't find markdown file with the id: accessing_accounts under conflux-portal
>     at C:\conflux\conflux-developer-site1\development\gen_each_lang_sidebars_config.js:50:21
>     at eachSidebarDoc (C:\conflux\conflux-developer-site1\development\gen_each_lang_sidebars_config.js:35:23)
>     at eachSidebarDoc (C:\conflux\conflux-developer-site1\development\gen_each_lang_sidebars_config.js:33:29)
>     at Object.keys.map.lang (C:\conflux\conflux-developer-site1\development\gen_each_lang_sidebars_config.js:113:11)
>     at Array.map (<anonymous>)
>     at C:\conflux\conflux-developer-site1\development\gen_each_lang_sidebars_config.js:108:29
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
After changed 
```js
   {
        type: "category",
        label: "Use Conflux In Browser With Portal",
        items: [
          { type: "doc", folder: "conflux-portal", id: "introduction" },
          { type: "doc", folder: "conflux-portal", id: "getting_started" },
          { type: "doc", folder: "conflux-portal", id: "accessing_accounts" },
          { type: "doc", folder: "conflux-portal", id: "sending_transactions" },
          { type: "doc", folder: "conflux-portal", id: "provider_api" },
          { type: "doc", folder: "conflux-portal", id: "signing_data_with_portal" },
        ]
      },
```
to 
```js
   {
        type: "category",
        label: "Use Conflux In Browser With Portal",
        items: [
       
        ]
      },
```
it works.

**Comment by yqrashawn** [comment]
You need to run `yarn RESET` the first time you clone this repo.

Checkou the readme [here](https://github.com/Conflux-Chain/conflux-developer-site#installation)

**Comment by yqrashawn** [comment]
You need to run `yarn RESET` the first time you clone this repo.

Checkout the readme [here](https://github.com/Conflux-Chain/conflux-developer-site#installation)
