### ISSUE TITLE
error when running `yarn start`

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/conflux-developer-site#31]
``` shell
❯ yarn start
yarn run v1.22.4
$ cfxdoc start
Starting the development server...
(node:62132) UnhandledPromiseRejectionWarning: Error: fatal: not a git repository: /Users/yqrashawn/workspace/office/conflux-devdocs/node_modules/conflux-docusaurus-config/docs/conflux-doc/../../.git/modules/docs/conflux-doc

    at GitExecutor.<anonymous> (/Users/yqrashawn/workspace/office/conflux-devdocs/node_modules/simple-git/src/lib/git-executor.js:39:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/yqrashawn/workspace/office/conflux-devdocs/node_modules/simple-git/src/lib/git-executor.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:62132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:62132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Failed to load ./.env.

✔ Client
  Compiled successfully in 9.06s

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/yqrashawn/workspace/office/conflux-devdocs/node_modules/conflux-docusaurus-config
ℹ ｢wds｣: 404s will fallback to /index.html

✔ Client
  Compiled successfully in 99.24ms

```

**Comment by yqrashawn** [comment]
Currently, the error can be safely ignored. It's Docusaurus trying to get the update time of each doc with `simple-git`.
`yarn build` will get the right date.

But it's indeed a bug.
